### ISSUE TITLE
meitulu大约12页后停止下载，任务无法继续

### ISSUE THREAD

**Issue by mayhuny** [Licoy/girls-reptile#13]
问题反馈：
1、meitulu采集过程中大约在12页左右任务会停止，开启任务后会从第一页采集。
2、部分图片未下载完，文件损坏。

软件版本：2。0.0

感谢！

**Comment by Licoy** [comment]
图片未下载完成，等待片刻之后看看是完整呢

**Comment by mayhuny** [comment]
等待后也是不完整的，另外2.0.1版本中还是存在采集一段时间后采集任务停止，无法继续，只能重新开始
