### ISSUE TITLE
网址提供

### ISSUE THREAD

**Issue by Tsingmark** [Licoy/girls-reptile#14]
www.nlegs.com

**Comment by Licoy** [comment]
此网站不挂代理则显示
```
Error 1020 Ray ID: 5179ccf35b0e7854 • 2019-09-17 08:44:51 UTC
Access denied
What happened?
This website is using a security service to protect itself from online attacks.
```

**Comment by Tsingmark** [comment]
这个确实需要挂代理；
要不你试试最经典的妹子图？
https://www.mzitu.com/


看你的版本可以自定义采集，那有没有考虑下个版本加一个搜索，全网站资源可能我只要某个人的图片，加个对抓取的名字的匹配，只下载部分图片；


------------------ 原始邮件 ------------------
发件人: "憧憬Licoy"<notifications@github.com>;
发送时间: 2019年9月17日(星期二) 下午4:45
收件人: "Licoy/girls-reptile"<girls-reptile@noreply.github.com>;
抄送: "曾棉锋"<805129473@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Licoy/girls-reptile] 网址提供 (#14)




此网站不挂代理则显示
 Error 1020 Ray ID: 5179ccf35b0e7854 • 2019-09-17 08:44:51 UTC Access denied What happened? This website is using a security service to protect itself from online attacks.

**Comment by Licoy** [comment]
挂代理的那个已经适配，不过妹子图的目前在测试中图片资源加请求头也是无济于事，可能是和download-manager有关
