### ISSUE TITLE
希望新增网站支持

### ISSUE THREAD

**Issue by huan5559** [Licoy/girls-reptile#15]
本来想修改一下json文件自己试试，不过搞了很久也没成功，希望下个版本能新增这个网站支持
https://girlimg.epio.app/article

**Comment by Licoy** [comment]
```
403
Sorry！该网站管理员禁止了你所在国家的IP地址访问
```
只有挂代理才可以访问

**Comment by Licoy** [comment]
目标站点含有漏点图片，仓库不予以支持，感谢您的使用！
