### ISSUE TITLE
建议增加对更多类型的图片网站的支持，如https://www.pexels.com

### ISSUE THREAD

**Issue by ipspring** [Licoy/girls-reptile#19]
## 想法内容
增加对更多布局类型的网站的支持，实现对更多图片网站的下载（功能更强大，自由度更高）。

小点子：通过json来设置是否分页等，来启用不同的解析模块，以便兼容只有一层的(非内外层的)网站和无分页的网站，例如：
https://www.pexels.com
https://www.pexels.com/zh-cn/popular-searches/
...
```

**Comment by Licoy** [comment]
可以，目前正在考虑此类网站以及异步加载的网站

**Comment by jieshuq** [comment]
希望也能增加  https://wallhaven.cc 这个网站。图片质量非常高

**Comment by Licoy** [comment]
本仓库已停止站点适配需求
