### ISSUE TITLE
采集异常

### ISSUE THREAD

**Issue by ipspring** [Licoy/girls-reptile#20]
## 软件版本
2.0.0
## 操作系统
windows10

#采集源规则如下，请问是不是图片的src是相对地址的原因？
`
{
        "name": "Pexels/免费素材照片", 
        "key":"Pexels",
        "url": "https://www.pexels.com/zh-cn/", 
        "tags": [
            {"name": "音樂", "url": "https://www.pexels.com/zh-cn/search/音樂"},
			{"name": "頭髮", "url": "https://www.pexels.com/zh-cn/search/頭髮"},
			{"name": "女孩", "url": "https://www.pexels.com/zh-cn/search/女孩"},
			{"name": "辦公桌", "url": "https://www.pexels.com/zh-cn/search/辦公桌"},
			{"name": "健身", "url": "https://www.pexels.com/zh-cn/search/健身"},
			{"name": "工作", "url": "https://www.pexels.com/zh-cn/search/工作"},
			{"name": "行銷", "url": "https://www.pexels.com/zh-cn/search/行銷"},
			{"name": "人群", "url": "https://www.pexels.com/zh-cn/search/人群"},
			{"name": "書籍", "url": "https://www.pexels.com/zh-cn/search/書籍"},
			{"name": "房屋", "url": "https://www.pexels.com/zh-cn/search/房屋"},
			{"name": "有創意的", "url": "https://www.pexels.com/zh-cn/search/有創意的"},
			{"name": "派對", "url": "https://www.pexels.com/zh-cn/search/派對"},
			{"name": "朋友", "url": "https://www.pexels.com/zh-cn/search/朋友"},
			{"name": "自然", "url": "https://www.pexels.com/zh-cn/search/自然"},
			{"name": "建造", "url": "https://www.pexels.com/zh-cn/search/建造"},
			{"name": "肖像", "url": "https://www.pexels.com/zh-cn/search/肖像"},
			{"name": "動物", "url": "https://www.pexels.com/zh-cn/search/動物"},
			{"name": "建築", "url": "https://www.pexels.com/zh-cn/search/建築"},
			{"name": "廚房", "url": "https://www.pexels.com/zh-cn/search/廚房"},
			{"name": "質地", "url": "https://www.pexels.com/zh-cn/search/質地"},
			{"name": "男性", "url": "https://www.pexels.com/zh-cn/search/男性"},
			{"name": "學校", "url": "https://www.pexels.com/zh-cn/search/學校"},
			{"name": "綠色", "url": "https://www.pexels.com/zh-cn/search/綠色"},
			{"name": "成功", "url": "https://www.pexels.com/zh-cn/search/成功"},
			{"name": "讀", "url": "https://www.pexels.com/zh-cn/search/讀"},
			{"name": "樣機", "url": "https://www.pexels.com/zh-cn/search/樣機"},
			{"name": "天空", "url": "https://www.pexels.com/zh-cn/search/天空"},
			{"name": "健身房", "url": "https://www.pexels.com/zh-cn/search/健身房"},
			{"name": "團隊", "url": "https://www.pexels.com/zh-cn/search/團隊"},
			{"name": "健康", "url": "https://www.pexels.com/zh-cn/search/健康"},
			{"name": "臉孔", "url": "https://www.pexels.com/zh-cn/search/臉孔"},
			{"name": "研究", "url": "https://www.pexels.com/zh-cn/search/研究"},
			{"name": "海", "url": "https://www.pexels.com/zh-cn/search/海"},
			{"name": "時間", "url": "https://www.pexels.com/zh-cn/search/時間"},
			{"name": "草", "url": "https://www.pexels.com/zh-cn/search/草"},
			{"name": "抽象", "url": "https://www.pexels.com/zh-cn/search/抽象"},
			{"name": "森林", "url": "https://www.pexels.com/zh-cn/search/森林"},
			{"name": "會議", "url": "https://www.pexels.com/zh-cn/search/會議"},
			{"name": "房間", "url": "https://www.pexels.com/zh-cn/search/房間"},
			{"name": "紐約城桌面", "url": "https://www.pexels.com/zh-cn/search/紐約城桌面"},
			{"name": "互聯網", "url": "https://www.pexels.com/zh-cn/search/互聯網"},
			{"name": "模特兒", "url": "https://www.pexels.com/zh-cn/search/模特兒"},
			{"name": "家庭成員", "url": "https://www.pexels.com/zh-cn/search/家庭成員"},
			{"name": "微笑", "url": "https://www.pexels.com/zh-cn/search/微笑"},
			{"name": "工作的", "url": "https://www.pexels.com/zh-cn/search/工作的"},
			{"name": "市", "url": "https://www.pexels.com/zh-cn/search/市"},
			{"name": "智慧手機", "url": "https://www.pexels.com/zh-cn/search/智慧手機"},
			{"name": "資料", "url": "https://www.pexels.com/zh-cn/search/資料"},
			{"name": "運動", "url": "https://www.pexels.com/zh-cn/search/運動"},
			{"name": "冬季", "url": "https://www.pexels.com/zh-cn/search/冬季"},
			{"name": "烹饪", "url": "https://www.pexels.com/zh-cn/search/烹饪"},
			{"name": "電話", "url": "https://www.pexels.com/zh-cn/search/電話"},
			{"name": "網站", "url": "https://www.pexels.com/zh-cn/search/網站"},
			{"name": "地球", "url": "https://www.pexels.com/zh-cn/search/地球"},
			{"name": "旅行", "url": "https://www.pexels.com/zh-cn/search/旅行"},
			{"name": "工具", "url": "https://www.pexels.com/zh-cn/search/工具"},
			{"name": "塗料", "url": "https://www.pexels.com/zh-cn/search/塗料"},
			{"name": "有趣", "url": "https://www.pexels.com/zh-cn/search/有趣"},
			{"name": "電腦", "url": "https://www.pexels.com/zh-cn/search/電腦"},
			{"name": "施工", "url": "https://www.pexels.com/zh-cn/search/施工"},
			{"name": "錢", "url": "https://www.pexels.com/zh-cn/search/錢"},
			{"name": "攝影", "url": "https://www.pexels.com/zh-cn/search/攝影"},
			{"name": "黑與白", "url": "https://www.pexels.com/zh-cn/search/黑與白"},
			{"name": "家", "url": "https://www.pexels.com/zh-cn/search/家"},
			{"name": "冰淇淋", "url": "https://www.pexels.com/zh-cn/search/冰淇淋"},
			{"name": "禮品", "url": "https://www.pexels.com/zh-cn/search/禮品"},
			{"name": "平面", "url": "https://www.pexels.com/zh-cn/search/平面"},
			{"name": "爱", "url": "https://www.pexels.com/zh-cn/search/爱"},
			{"name": "釀酒", "url": "https://www.pexels.com/zh-cn/search/釀酒"},
			{"name": "街道", "url": "https://www.pexels.com/zh-cn/search/街道"},
			{"name": "筆記本", "url": "https://www.pexels.com/zh-cn/search/筆記本"},
			{"name": "非洲", "url": "https://www.pexels.com/zh-cn/search/非洲"},
			{"name": "輕的", "url": "https://www.pexels.com/zh-cn/search/輕的"},
			{"name": "寶寶", "url": "https://www.pexels.com/zh-cn/search/寶寶"},
			{"name": "手機", "url": "https://www.pexels.com/zh-cn/search/手機"},
			{"name": "紙", "url": "https://www.pexels.com/zh-cn/search/紙"},
			{"name": "老", "url": "https://www.pexels.com/zh-cn/search/老"},
			{"name": "山脈", "url": "https://www.pexels.com/zh-cn/search/山脈"},
			{"name": "情侶", "url": "https://www.pexels.com/zh-cn/search/情侶"},
			{"name": "宇宙", "url": "https://www.pexels.com/zh-cn/search/宇宙"},
			{"name": "火", "url": "https://www.pexels.com/zh-cn/search/火"},
			{"name": "河", "url": "https://www.pexels.com/zh-cn/search/河"},
			{"name": "花卉", "url": "https://www.pexels.com/zh-cn/search/花卉"},
			{"name": "假日", "url": "https://www.pexels.com/zh-cn/search/假日"},
			{"name": "蘋果手機", "url": "https://www.pexels.com/zh-cn/search/蘋果手機"},
			{"name": "學生", "url": "https://www.pexels.com/zh-cn/search/學生"},
			{"name": "高清桌面", "url": "https://www.pexels.com/zh-cn/search/高清桌面"},
			{"name": "雲", "url": "https://www.pexels.com/zh-cn/search/雲"},
			{"name": "模糊", "url": "https://www.pexels.com/zh-cn/search/模糊"},
			{"name": "社交媒體", "url": "https://www.pexels.com/zh-cn/search/社交媒體"},
			{"name": "商業", "url": "https://www.pexels.com/zh-cn/search/商業"},
			{"name": "安全", "url": "https://www.pexels.com/zh-cn/search/安全"},
			{"name": "心臟", "url": "https://www.pexels.com/zh-cn/search/心臟"},
			{"name": "人", "url": "https://www.pexels.com/zh-cn/search/人"},
			{"name": "度假", "url": "https://www.pexels.com/zh-cn/search/度假"},
			{"name": "设计", "url": "https://www.pexels.com/zh-cn/search/设计"},
			{"name": "文章", "url": "https://www.pexels.com/zh-cn/search/文章"},
			{"name": "地圖", "url": "https://www.pexels.com/zh-cn/search/地圖"},
			{"name": "日落", "url": "https://www.pexels.com/zh-cn/search/日落"},
			{"name": "雨", "url": "https://www.pexels.com/zh-cn/search/雨"},
			{"name": "快樂", "url": "https://www.pexels.com/zh-cn/search/快樂"},
			{"name": "汽車", "url": "https://www.pexels.com/zh-cn/search/汽車"},
			{"name": "美女", "url": "https://www.pexels.com/zh-cn/search/美女"},
			{"name": "蘋果", "url": "https://www.pexels.com/zh-cn/search/蘋果"},
			{"name": "咖啡", "url": "https://www.pexels.com/zh-cn/search/咖啡"},
			{"name": "冒險", "url": "https://www.pexels.com/zh-cn/search/冒險"},
			{"name": "海灘", "url": "https://www.pexels.com/zh-cn/search/海灘"},
			{"name": "晚上", "url": "https://www.pexels.com/zh-cn/search/晚上"},
			{"name": "風景", "url": "https://www.pexels.com/zh-cn/search/風景"},
			{"name": "女人", "url": "https://www.pexels.com/zh-cn/search/女人"},
			{"name": "跳舞", "url": "https://www.pexels.com/zh-cn/search/跳舞"},
			{"name": "時尚", "url": "https://www.pexels.com/zh-cn/search/時尚"},
			{"name": "衣服", "url": "https://www.pexels.com/zh-cn/search/衣服"},
			{"name": "樹", "url": "https://www.pexels.com/zh-cn/search/樹"},
			{"name": "相機", "url": "https://www.pexels.com/zh-cn/search/相機"},
			{"name": "筆電", "url": "https://www.pexels.com/zh-cn/search/筆電"},
			{"name": "內部", "url": "https://www.pexels.com/zh-cn/search/內部"},
			{"name": "水", "url": "https://www.pexels.com/zh-cn/search/水"},
			{"name": "沙漠", "url": "https://www.pexels.com/zh-cn/search/沙漠"},
			{"name": "星星", "url": "https://www.pexels.com/zh-cn/search/星星"},
			{"name": "瑜伽", "url": "https://www.pexels.com/zh-cn/search/瑜伽"},
			{"name": "理念", "url": "https://www.pexels.com/zh-cn/search/理念"},
			{"name": "紐約", "url": "https://www.pexels.com/zh-cn/search/紐約"},
			{"name": "結婚典禮", "url": "https://www.pexels.com/zh-cn/search/結婚典禮"},
			{"name": "賽跑", "url": "https://www.pexels.com/zh-cn/search/賽跑"},
			{"name": "太陽", "url": "https://www.pexels.com/zh-cn/search/太陽"},
			{"name": "空間", "url": "https://www.pexels.com/zh-cn/search/空間"},
			{"name": "年輕", "url": "https://www.pexels.com/zh-cn/search/年輕"},
			{"name": "辦公室", "url": "https://www.pexels.com/zh-cn/search/辦公室"},
			{"name": "工作", "url": "https://www.pexels.com/zh-cn/search/工作"},
			{"name": "浪漫的", "url": "https://www.pexels.com/zh-cn/search/浪漫的"},
			{"name": "自然桌面", "url": "https://www.pexels.com/zh-cn/search/自然桌面"},
			{"name": "技術", "url": "https://www.pexels.com/zh-cn/search/技術"},
			{"name": "化妝", "url": "https://www.pexels.com/zh-cn/search/化妝"},
			{"name": "藝術", "url": "https://www.pexels.com/zh-cn/search/藝術"},
			{"name": "孩子", "url": "https://www.pexels.com/zh-cn/search/孩子"},
			{"name": "電腦桌面", "url": "https://www.pexels.com/zh-cn/search/電腦桌面"},
			{"name": "醫", "url": "https://www.pexels.com/zh-cn/search/醫"},
			{"name": "花園", "url": "https://www.pexels.com/zh-cn/search/花園"},
			{"name": "人", "url": "https://www.pexels.com/zh-cn/search/人"},
			{"name": "牆壁", "url": "https://www.pexels.com/zh-cn/search/牆壁"},
			{"name": "金融", "url": "https://www.pexels.com/zh-cn/search/金融"},
			{"name": "生意人", "url": "https://www.pexels.com/zh-cn/search/生意人"},
			{"name": "放鬆", "url": "https://www.pexels.com/zh-cn/search/放鬆"},
			{"name": "訓練", "url": "https://www.pexels.com/zh-cn/search/訓練"},
			{"name": "行業", "url": "https://www.pexels.com/zh-cn/search/行業"},
			{"name": "傷心", "url": "https://www.pexels.com/zh-cn/search/傷心"},
			{"name": "夏季", "url": "https://www.pexels.com/zh-cn/search/夏季"},
			{"name": "木頭", "url": "https://www.pexels.com/zh-cn/search/木頭"},
			{"name": "馬路", "url": "https://www.pexels.com/zh-cn/search/馬路"},
			{"name": "通訊", "url": "https://www.pexels.com/zh-cn/search/通訊"},
			{"name": "餐饮", "url": "https://www.pexels.com/zh-cn/search/餐饮"},
			{"name": "樹木", "url": "https://www.pexels.com/zh-cn/search/樹木"},
			{"name": "组", "url": "https://www.pexels.com/zh-cn/search/组"}

        ], 
        "pages": {
            "element": "body div.page-wrap div.l-container div.photos div.photos__column article", 
            "name": {
                "element": "a:first-child img",
                "attr": "alt"
            },
            "url": {
                "element": "a:first-child",
                "attr": "href",
                "needMerge": true
            },
            "nextPageUrlMode": {
                "mode": "add",  
                "addValue": ""
            }, 
            "lastPage": {
                "element": "", 
                "minPageLength": 2, 
                "attr": "@text", 
                "descIndex": 2, 
                "isNeedSplit": false, 
                "splits": []
            }
        }, 
        "imgs": {
            "element": "div.photo-page__photo > a.js-photo-page-image-download-link",
            "nextPageUrlMode": {
                "incrementMode": "",
                "mode": "add", 
                "addValue": ""
            }, 
            "lastPage": {
                "element": "", 
                "minPageLength": 2, 
                "attr": "@text", 
                "descIndex": 2, 
                "isNeedSplit": false, 
                "splits": []
            }
        }, 
        "supportReptileVersion": 1
    }
`

**Comment by Licoy** [comment]
整体的采集规则是一个集合，最外层要用[]包括起来
