### ISSUE TITLE
希望新站点采集

### ISSUE THREAD

**Issue by iloter** [Licoy/girls-reptile#23]
希望新增fetcherx采集
### https://fetcherx.com/
fetcherx是一个类似RSS工具，可以添加`Rss/Youtube/Twitter/Instagram/Microsoft/Google Pixel/apple/Tumblr`源
比如添加某个推特源：https://app.fetcherx.com/social/twitter/NothingWe
或者是添加的Rss订阅，点击封面查看完整套图，但是在fetcherx网站内：https://app.fetcherx.com/rss/02920fe6759b55b83a10f84ce3a0a1b9
ins源：https://app.fetcherx.com/social/instagram/googlepixel

**Comment by Licoy** [comment]
目前本仓库已关闭站点支持
