### ISSUE TITLE
代理可以软件内置吗

### ISSUE THREAD

**Issue by lyydhy** [Licoy/girls-reptile#28]
## 想法内容
```
感谢您提交您的idea，尽可能的描述清楚可以帮助我们更好的理解~
```
新版本有个图源是需要代理的 但是我代理开了全局 pac  都不行  所以可以软件内置一下这个功能吗

**Comment by 119977** [comment]
他的意思是说怎么内置代理，而不是使用全局代理，就像我们现在都在用SSR，除了全局代理怎么为软件单独设置代理，其实是有一个软件代理外挂软件的，只是很多人都没用过

**Comment by Licoy** [comment]
软件只要你开启小飞机的全局代理就可以正常访问使用了 @119977 @lyydhy
