### ISSUE TITLE
最新10.15 mac上无法打开

### ISSUE THREAD

**Issue by cuttino001** [Licoy/girls-reptile#36]
10.15 mac 打开提示：
![image](https://user-images.githubusercontent.com/4423485/66879563-36611680-eff1-11e9-80a4-4f1056df8429.png)

**Comment by Licoy** [comment]
没有任何异常说明么，我的macos版本也是最新的10.15完全没得问题呀

**Comment by cuttino001** [comment]
> 没有任何异常说明么，我的macos版本也是最新的10.15完全没得问题呀

就这样一个弹框，没有其他日志。

**Comment by Licoy** [comment]
> > 没有任何异常说明么，我的macos版本也是最新的10.15完全没得问题呀
> 
> 就这样一个弹框，没有其他日志。

重试呢
