### ISSUE TITLE
source site request

### ISSUE THREAD

**Issue by figurion** [Licoy/girls-reptile#4]
quantuwang.co/meinv/
nvshens.com

**Comment by Licoy** [comment]
Thank you for submitting, we will be in the next version to support the site you provide.

**Comment by Licoy** [comment]
nvshens.com -> https://www.nvshens.net/

**Comment by Licoy** [comment]
quantuwang.co/meinv/ 已进行适配，nvshens.com未显示总页码，暂不支持适配
